spring.application.name=DentalPlus_Backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://7a6n08.h.filess.io:61002/DentalPlusBD_middlehide?useUnicode=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:DentalPlusBD_middlehide}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:83da726aa4bc6e3e3c0fe86a85477bccd49e237f}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=5000
spring.datasource.hikari.max-lifetime=15000
spring.datasource.hikari.connection-timeout=10000

server.address=0.0.0.0
server.port=${PORT:8080}

cloudinary.url=${CLOUDINARY_URL:cloudinary://397793455713667:oEyfAYrtBArDakE2U5VQiPiUT3Q@dffzuxmmu}

supabase.url=${SUPABASE_URL:https://mwlauwysveyxydpjkgwu.supabase.co}
supabase.key=${SUPABASE_KEY:sb_secret_NCtnLhG8g-pvlUa_Bm7z-g_EIzgzDTo}
supabase.bucket.documents=${SUPABASE_BUCKET_DOCUMENTS:documents}

auth.token.private-key=${AUTH_TOKEN_PRIVATE_KEY:-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCiQvHqSyqRxZe+\nah+MuMVL9Bu53ANFXonoe7l89toZJFt2G41mKg/b9ZFsHmCBbwH9PlnZB45kvzdp\nWKgX6CB0EcSuEO1hFZQmpQ9wIhJqcb73B4zuKc3+4ZUL/LNMUmW3LztTuLnicBth\nkzBSf3wij0xBH2ZyMKqbayGoStCU+sHjvRr4rg/7Bpuw7/6tXd4rOYW7cmtzlrEl\nhOjLaEv7LaqtHfcTimuTIf2aEbGtZb8ZSjUuXzXZ5MPROmAXXmBqUQ9xxHYz5MYw\nSJiqO7hrxZKqPwxKXj4YJpq+WUzAYl02gA6p9O6ANlNmfxpxJkMSF6Kn3DIICVdu\nFk6P00s3AgMBAAECggEAEvlrGppsQZxD5gi45Gwdk4fZz35yhM53p/pX3XdsV5ul\nyluRybb0yyRIkMZt7eonkbqUfR7iFYE6yenhIN03IPuMQ/fyGkk7XYLYbvoSVzoy\nj5E6zLA8yNJjldbuDJMSFpLCXZmbZbxK/Lpeizch3VS5IQsP9XMgGt6IkrUfoQa7\nXNJP0W7Jwfua9385IQhGrhTUxqeFNyZXgdZ2YLlZjzGKbBSXIgCTQxlzXiF+rR26\nLdtHDpaFeBvhOvssFRLnPCt4cuak3Hd4gQNpJvxLXbxp8RJrIK+b2e679LbcVBhY\nixXOd+P38+6RMYuRl7D5cUz9N0QGriR3uuvk3iiaqQKBgQDMq8X98g8xIhHDJKOc\nKKNp5Q7ullxvt0doLNf4QiciOCWbxJ927vCBaNVYaaBu23hzQe5L6U4pWIe4tqvl\n4z+RwYXEM4um3Obi9pAqDoO6cZvwTO1peoEZfLJfPgOKiL0VIHF8/jOc0ztOxGSh\nYPDV4dMFBM/2qtOhzmitDzEZ1QKBgQDK9GkF8NqllsJUOtonhI8VKO59VE9MaDN+\nMI/kkjdMo998GPPMaFrk4xdCt0oSr6mv497Taqv3HdnuVglKwAHYs1OKdDj5R+d2\njlYpeGJdbHJEIC1GM05r6yu0QRhy9h370hnJGVFrbDQGJ6l7yzWwdK1JruXzyLYW\nNH8EO6Bq2wKBgEal7HwR+Ah/uB3iIc+ff3joJlVY9aNiYnWlNQ9u1k9Ljj/MiTbm\nl4I0C6CvJT/e5h7y3Sy65c4DzyWFeKSr4p+Pa3skR8pbah9h+LVruTC8UpWKGFFW\nhgWkM3YI0/QX6xzFzCbXID279DbmN840xi0t/Ec5OAfvQ4oQ07UZD1vZAoGAYU66\nJA0M6CPWXIgzHItkBuMvJYwM0TeMqM4jz5WDSg2wE1HrYnAOVHvFJUm4DCmJFDoP\nFhKpDLyVRr6diedxezLPtSxwPKULBz7LdOqxTtW2G4/J5USoLvn8ZFppnIUAb0KW\n9mJbNUQV1XWivyX5QfdPNmrS+gWbuB3HYIIuMc0CgYEAvtlbwNieRZz7kZa7PKCq\nVdB/161P0iVpyoBoSKe0zZdmYTxytiAd4tkWZ+8F1QLZnPNZavmUkx3N3/k//pJk\nbp4nvKRKcsFC/A+/qWYOvGKA0g79GGpEJtTn14FYzPrSGQQqMld3t4t/8mdjjSdX\nMC5cAt1jFmnYiqSgP7pbo2I=\n-----END PRIVATE KEY-----\n}
auth.token.public-key=${AUTH_TOKEN_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAokLx6ksqkcWXvmofjLjF\nS/QbudwDRV6J6Hu5fPbaGSRbdhuNZioP2/WRbB5ggW8B/T5Z2QeOZL83aVioF+gg\ndBHErhDtYRWUJqUPcCISanG+9weM7inN/uGVC/yzTFJlty87U7i54nAbYZMwUn98\nIo9MQR9mcjCqm2shqErQlPrB470a+K4P+wabsO/+rV3eKzmFu3Jrc5axJYToy2hL\n+y2qrR33E4prkyH9mhGxrWW/GUo1Ll812eTD0TpgF15galEPccR2M+TGMEiYqju4\na8WSqj8MSl4+GCaavllMwGJdNoAOqfTugDZTZn8acSZDEheip9wyCAlXbhZOj9NL\nNwIDAQAB\n-----END PUBLIC KEY-----\n}
auth.token.expiration-ms=${AUTH_TOKEN_EXPIRATION_MS:604800000}

spring.profiles.active=hibernate